# Generated by Django 4.1.7 on 2023-03-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='op1c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='op2c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='op3c',
            field=models.IntegerField(default=0),
        ),
    ]
