# Generated by Django 4.1.7 on 2023-03-26 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pollapp', '0002_studentmodel_op1c_studentmodel_op2c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
